MODEL:
  WEIGHT: "catalog://ImageNetPretrained/DLA34"
INPUT:
  FLIP_PROB_TRAIN: 0.5
  SHIFT_SCALE_PROB_TRAIN: 0.3
DATASETS:
  DETECT_CLASSES: ("bicycle", "bus", "car", "construction_vehicle", "motorcycle", "pedestrian", "trailer", "truck")
  MAX_OBJECTS: 128
  TRAIN: ("nusc_train_half",)
  TEST: ("nusc_test",)
SOLVER:
  BASE_LR: 5.0e-4
  STEPS: (200000, 250000)
  MAX_ITERATION: 300000
  IMS_PER_BATCH: 32
  CHECKPOINT_PERIOD: 500